CREATE WAREHOUSE IF NOT EXISTS UNIVERSITY_WH
WITH
WAREHOUSE_SIZE='X-SMALL'
AUTO_SUSPEND=60
AUTO_RESUME=TRUE;

-- shows warehouses
SHOW WAREHOUSES;


-- creating a database
CREATE OR REPLACE DATABASE UNIVERSITY_DB;

-- creating schemas
CREATE SCHEMA UNIRAW;
CREATE SCHEMA UNICORE;
CREATE SCHEMA UNIMART;

-- shows schema
SHOW SCHEMAS;


--setting the context
USE WAREHOUSE UNIVERSITY_WH;
USE DATABASE UNIVERSITY_DB ;
USE SCHEMA UNIRAW;
