-- =====================================================
-- SETTING UP THE CONTEXT
-- =====================================================


USE WAREHOUSE UNIVERSITY_WH;

USE DATABASE UNIVERSITY_DB;

USE SCHEMA UNIRAW;


-- =====================================================
-- CREATE SNOWPIPES FOR CSV FILES
-- =====================================================

-- STUDENT PIPE

CREATE OR REPLACE PIPE STUDENT_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO STUDENT_RAW
FROM @UNIVERS_CSV_STAGE
PATTERN='.*students.*[.]csv'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);


-- FACULTY PIPE

CREATE OR REPLACE PIPE FACULTY_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO FACULTY_RAW
FROM @UNIVERS_CSV_STAGE
PATTERN='.*faculty.*[.]csv'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);


-- COURSE PIPE

CREATE OR REPLACE PIPE COURSE_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO COURSE_RAW
FROM @UNIVERS_CSV_STAGE
PATTERN='.*courses.*[.]csv'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);


-- EXAMINATION PIPE

CREATE OR REPLACE PIPE EXAMINATION_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO EXAMINATION_RAW
FROM @UNIVERS_CSV_STAGE
PATTERN='.*examination.*[.]csv'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);


-- RESULT PIPE

CREATE OR REPLACE PIPE RESULT_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO RESULT_RAW
FROM @UNIVERS_CSV_STAGE
PATTERN='.*results.*[.]csv'
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);



-- CREATE SNOWPIPE FOR JSON FILE


-- ATTENDANCE JSON PIPE

CREATE OR REPLACE PIPE ATTENDANCE_PIPE
AUTO_INGEST = TRUE
AS
COPY INTO ATTENDANCE_RAW
FROM @UNIVERS_JSON_STAGE
PATTERN='.*attendance.*[.]json'
FILE_FORMAT = (FORMAT_NAME = JSON_FORMAT);



-- SHOW PIPES


SHOW PIPES;



-- REFRESH PIPES


ALTER PIPE STUDENT_PIPE REFRESH;

ALTER PIPE FACULTY_PIPE REFRESH;

ALTER PIPE COURSE_PIPE REFRESH;

ALTER PIPE EXAMINATION_PIPE REFRESH;

ALTER PIPE RESULT_PIPE REFRESH;

ALTER PIPE ATTENDANCE_PIPE REFRESH;


-- =====================================================
-- VERIFY DATA
-- =====================================================

SELECT COUNT(*) FROM STUDENT_RAW;

SELECT COUNT(*) FROM FACULTY_RAW;

SELECT COUNT(*) FROM COURSE_RAW;

SELECT COUNT(*) FROM EXAMINATION_RAW;

SELECT COUNT(*) FROM RESULT_RAW;

SELECT COUNT(*) FROM ATTENDANCE_RAW;