
-- SETTING UP CONTEXT


USE WAREHOUSE UNIVERSITY_WH;

USE DATABASE UNIVERSITY_DB;

USE SCHEMA UNICORE;



-- FLATTENING JSON DATA


SELECT VALUE
FROM UNIRAW.ATTENDANCE_RAW,
LATERAL FLATTEN (INPUT => RAW_DATA);



-- EXTRACTING JSON DATA INTO TABLE


CREATE OR REPLACE TABLE ATTENDANCE_CORE AS

SELECT
    VALUE:studentId::STRING AS studentId,
    VALUE:attendancePercentage::INT AS attendancePercentage,
    VALUE:status::STRING AS status

FROM UNIRAW.ATTENDANCE_RAW,
LATERAL FLATTEN (INPUT => RAW_DATA);



-- VIEWING DATA


SELECT * FROM ATTENDANCE_CORE;

SELECT COUNT(*) FROM ATTENDANCE_CORE;